[package]
edition = "2021"
name = "anoma-generic-call-circuit"
version = "1.0.0"

[workspace]

[dependencies]
anoma-generic-call-library = { path = "../generic_call_library" }
anoma-generic-call-witness = { path = "../generic_call_witness" }
anoma-rm-risc0 = { git = "https://github.com/anoma/arm-risc0.git", tag = "v2.0.0-rc.4", default-features = false }
risc0-zkvm = "3.0.3"
